spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./.local/sword_forge_local;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  h2:
    console:
      enabled: true

app:
  security:
    enabled: ${APP_SECURITY_ENABLED:true}
